### ISSUE TITLE
关于popup组件的设计方式

### ISSUE THREAD

**Issue by lsert** [JeromeLin/dragon-ui#116]
不是很理解popup为什么要嵌套在组件内部的形式去做了呢，而不是用放置在最外层。
我能理解关于定位复杂的问题，包括检测外部变化需要重新更新的定位的问题
但是针对于dropdown和Select等一些其他的大型的弹框组件，外部的overflow的影响是很大的，开发的时候需要时刻注意这个问题。
而且针对小的tip组件，每个按钮去嵌套一个tip也会产生大量的组件，不能做到复用同一个popup。

**Comment by JeromeLin** [comment]
后面会用createPortal方式创建节点在body底部

**Comment by fjcgreat** [comment]
react native 似乎也可以利用 AppRegistry.setWrapperComponentProvider 输出到最外层。

**Comment by JeromeLin** [comment]
@fjcgreat zarm-web是PC端组件库，不涉及react-native。

**Comment by fjcgreat** [comment]
😢，我看的是 zarm库
