### ISSUE TITLE
Alert组件某些情况下传入theme无效

### ISSUE THREAD

**Issue by lsert** [JeromeLin/dragon-ui#144]
version: dragon-ui@1.0.0-alpha.26

应该是 定义了 alert组件的color值，导致传入任何的theme都是显示同一个颜色。

https://codesandbox.io/s/determined-bohr-xe915?fontsize=14

代码片段如下
https://github.com/JeromeLin/zarm-web/blob/a7de884309f6c27d23b50e396d667a192b7b4d50/components/alert/style/component.scss#L7-L14

是否可以考虑去除

**Comment by JeromeLin** [comment]
https://github.com/JeromeLin/zarm-web/commit/9c59d224a41d9d45ddcca1463bdcd99bbd0d8376
