### ISSUE TITLE
dev-dragon-ui分支下的Select组件未过滤粘贴内容导致的‘检索为空’

### ISSUE THREAD

**Issue by Krystal-wang-bg** [JeromeLin/dragon-ui#169]
dev-dragon-ui分支：
Select组件在可输入状态下，对于粘贴进去的内容没有过滤输入内容的样式等，带样式的搜索会导致虚假的"没有找到数据"

**Comment by JeromeLin** [comment]
全新版本开发中，历史版本不再提供增强性功能迭代。
