### ISSUE TITLE
Icon 没有定义默认样式

### ISSUE THREAD

**Issue by stbui** [JeromeLin/dragon-ui#174]
1. 在使用中发现垂直居中会略微偏上，需要设置display：inline-block
2. className 设置不生效
3. 没有指定icon默认大小

**Comment by JeromeLin** [comment]
![image](https://user-images.githubusercontent.com/9812721/66543048-dd176400-eb66-11e9-9a3b-8a9211d1bd49.png)
有？

**Comment by stbui** [comment]
可能我这边代码不是最新的
