### ISSUE TITLE
使用typeof的判断会导致隐含的问题

### ISSUE THREAD

**Issue by lsert** [JeromeLin/dragon-ui#31]
https://github.com/JeromeLin/dragon-ui/blob/d2b209f4726a8f9cf46facdf705ab2ac70292638/components/Table/Table.jsx#L177-L188

这边的处理可能会导致报错。render在变为 render() 或value的时候 很大几率会为null。
使用typeof判断object, 值为null的时候 会导致一些隐含的问题。

**Comment by JeromeLin** [comment]
you can use version 0.1.0-beta.3, it fixed the bug. thanks
