### ISSUE TITLE
this.setDropdown 的第二个参数应该为函数类型。

### ISSUE THREAD

**Issue by lsert** [JeromeLin/dragon-ui#32]
https://github.com/JeromeLin/dragon-ui/blob/d2b209f4726a8f9cf46facdf705ab2ac70292638/components/Select/Select.jsx#L133-L166

this.setDropdown(false, this.props.onChange(selected));  
应该为 this.setDropdown(false, ()=>{
  this.props.onChange(selected);
});

或 callback && callback() 执行前需要判断 callback的类型，开发者在onChange中返回的值类型不可确定。

**Comment by JeromeLin** [comment]
计划重构中。
