### ISSUE TITLE
Modal是否可以考虑兼容style或是动态层级覆盖

### ISSUE THREAD

**Issue by Krystal-wang-bg** [JeromeLin/dragon-ui#95]

**Comment by Krystal-wang-bg** [comment]
场景：目前多个Modal之间的覆盖顺序取决于render里面手写的顺序，而不是后出现的弹窗覆盖前面的弹窗，所以需要有style可以去强制弹窗的Z-index关系，或者做到Modal动态层级覆盖

1.可支持手写style强制Modal的ZIndex  2.做到动态层级覆盖，即窗口有多个Modal时，后显示的Modal动态覆盖之前显示的Modal

**Comment by JeromeLin** [comment]
1.我们不建议在弹层上二次弹层，这种交互方式违背了我们的交互规范，所以尽可能的避免这么做。
2.目前的做法是初始化就生成了相关dom节点，所以取决于render里面的手写顺序，这点是需要改进的，后续将改写dom的产生机制，可以做到动态层级的覆盖，即后打开的窗口将覆盖先打开的。
